[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*", "https://media.decentralized-content.com/.*"]

[build]
  command = "bun run build"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NPM_FLAGS = "--no-optional"

[functions]
  node_bundler = "esbuild"

# Specify external dependencies to be bundled
[[build.external]]
  name = "react"
  path = "node_modules/react"

[[build.external]]
  name = "react-dom"
  path = "node_modules/react-dom"

[[plugins]]
  package = "@netlify/plugin-nextjs"
